# miniconda bootstrap from conda-forge recipe
matrix:
  fast_finish: true

environment:
  matrix:
    - CONDA_PY: 35
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - CONDA_PY: 27
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"

platform:
  - x64

build: off

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set show_channel_urls true
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes -c defaults conda=4.3.29
  - cmd: conda config --set auto_update_conda false
  - cmd: conda install --yes -c conda-forge nbconvert

test_script:
  - cmd: echo "ok"
